apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${JOB_NAME}-${BRANCH}
  labels:
    app: ${JOB_NAME}-${BRANCH}
spec:
  selector:
    matchLabels:
      app: ${JOB_NAME}-${BRANCH}
  replicas: ${REPLICAS}
  template:
    metadata:
      labels:
        app: ${JOB_NAME}-${BRANCH}
    spec:
      containers:
      - name: ${JOB_NAME}-${BRANCH}
        image: ${DOCKER_REGISTRY_SERVER}/${DOCKER_REGISTRY_USER}/${JOB_NAME}:${BRANCH}.${BUILD_NUMBER}
        args:
        - /server
        livenessProbe:
          httpGet:
            path: /${BRANCH}
            port: 8080
            httpHeaders:
            - name: authorization
              value: teste
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /${BRANCH}
            port: 8080            
            httpHeaders:
            - name: authorization
              value: teste
          initialDelaySeconds: 30
          periodSeconds: 30
        imagePullPolicy: Always
        env:
        - name: DATABASE_URI
          value: "jdbc:sqlserver://${DATABASE_SERVER};database=teste"
        - name: DATABASE_USER
          value: "${DATABASE_USER}"
        - name: DATABASE_PASSWORD
          value: "${DATABASE_PASSWORD}"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
