apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microservice-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /master
        backend:
          serviceName: microservice-master
          servicePort: 8080
      - path: /master/*
        backend:
          serviceName: microservice-master
          servicePort: 8080
      - path: /blue
        backend:
          serviceName: microservice-blue
          servicePort: 8080
      - path: /blue/*
        backend:
          serviceName: microservice-blue
          servicePort: 8080