apiVersion: 1.0
kind: Deployment
metadata:
  name: testes:latest
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: testes:latest
    spec:
      containers:
      - name: testes-container
        image: laurowag/testes:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME